### ISSUE TITLE
Parsing error on auth migration

### ISSUE THREAD

**Issue by gascenciom1998** [supabase-community/firebase-to-supabase#5]
I get the following error when attempting to run `node import_users.js users.json`. I've followed all the instructions on the README for Auth migration, running locally (not fly.io). My users.json file looks well-formed on instpection.

console.logging seems to indicate the error ocurrs on `runSQL` but not sure exactly what is wrong.

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: Parser cannot parse input: expected ','
    at Parser._processBuffer (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/Parser.js:291:76)
    at Parser._transformBuffer (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/utils/Utf8Stream.js:24:10)
    at Parser._transform (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/utils/Utf8Stream.js:19:10)
    at Parser.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Parser.Writable.write (node:internal/streams/writable:334:10)
    at Chain._write (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-chain/index.js:152:18)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
Emitted 'error' event on Chain instance at:
    at Chain.<anonymous> (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-chain/index.js:146:71)
    at Chain.emit (node:events:402:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by burggraf** [comment]
I would try this: 

- install ts-node (`npm i ts-node -g`)
- run `ts-node import_users.ts users.json` to see if you get a clearer error message 

Looking at [import_users.ts](https://github.com/supabase-community/firebase-to-supabase/blob/main/auth/import_users.ts) I see `JSON.parse` is used to parse  your `supabase-service.json` file, so maybe the error is coming from that?  Have you verified that file is correct?

**Comment by gascenciom1998** [comment]
Thanks! @burggraf  I'm confident that `supabase-service.json` is correct. console-logging makes it seem like the error is con `client.query`

Doing what you suggested throws me the following error

```
ts-node import_users.ts users.json 1
/usr/local/lib/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
import_users.ts:24:5 - error TS7034: Variable 'pgCreds' implicitly has type 'any' in some locations where its type cannot be determined.

24 let pgCreds;
       ~~~~~~~
import_users.ts:47:15 - error TS7005: Variable 'pgCreds' implicitly has an 'any' type.

47         user: pgCreds.user,
                 ~~~~~~~
import_users.ts:48:15 - error TS7005: Variable 'pgCreds' implicitly has an 'any' type.

48         host: pgCreds.host,
                 ~~~~~~~
import_users.ts:49:19 - error TS7005: Variable 'pgCreds' implicitly has an 'any' type.

49         database: pgCreds.database,
                     ~~~~~~~
import_users.ts:50:19 - error TS7005: Variable 'pgCreds' implicitly has an 'any' type.

50         password: pgCreds.password,
                     ~~~~~~~
import_users.ts:51:15 - error TS7005: Variable 'pgCreds' implicitly has an 'any' type.

51         port: pgCreds.port
                 ~~~~~~~
import_users.ts:68:13 - error TS7034: Variable 'insertRows' implicitly has type 'any[]' in some locations where its type cannot be determined.

68         let insertRows = [];
               ~~~~~~~~~~
import_users.ts:83:35 - error TS7006: Parameter 'data' implicitly has an 'any' type.

83         pipeline.on('data', async data => {
                                     ~~~~
import_users.ts:84:24 - error TS7006: Parameter 'item' implicitly has an 'any' type.

84           data.forEach(item => {
                          ~~~~
import_users.ts:96:44 - error TS7005: Variable 'insertRows' implicitly has an 'any[]' type.

96           const result = await insertUsers(insertRows);
                                              ~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [
    7034, 7005, 7005,
    7005, 7005, 7005,
    7034, 7006, 7006,
    7005
  ]
}
```

**Comment by gascenciom1998** [comment]
Fixed the typing errors and got this error @burggraf 

```
/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/Parser.js:291
            if (index < this._buffer.length || this._done) return callback(new Error("Parser cannot parse input: expected ','"));
                                                                           ^
Error: Parser cannot parse input: expected ','
    at Parser._processBuffer (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/Parser.js:291:76)
    at Parser._transformBuffer (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/utils/Utf8Stream.js:24:10)
    at Parser._transform (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-json/utils/Utf8Stream.js:19:10)
    at Parser.Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Parser.Writable.write (node:internal/streams/writable:334:10)
    at Chain._write (/Users/gerardoascenciomorales/Documents/firebase-to-supabase/node_modules/stream-chain/index.js:152:18)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
```

**Comment by gascenciom1998** [comment]
The error turned out to relate to the users.json, which for some reason was missing some commas

**Comment by kiptoomm** [comment]
@gascenciom1998 @burggraf for those of us who can't use TS yet, this PR would fix the issue: https://github.com/supabase-community/firebase-to-supabase/pull/9

**Comment by roblonj** [comment]
> 

@gascenciom1998 How did you fix this? I have followed the instructions on README and still getting this error

**Comment by gascenciom1998** [comment]
@roblonj If I recall correctly I did something like the following:

I ran these commands
```
npm i ts-node -g
ts-node import_users.ts users.json
```

Then had to manually fix some type errors.
Then had to manually fix the formatting of user.json because the script was expecting it to have a couple of commas that it didn't have.
